import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/redux/provider/reduxProvider";
import { ThemeProvider } from "@/components/ui/theme-provider";
import "dotenv/config";
import { env } from "../../env.mjs";
import Script from 'next/script';

const inter = Inter({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Cloudcraft",
  description: "Generated by create next app",
};

const MapScriptUrl = `https://apis.mappls.com/advancedmaps/api/${env.NEXT_PUBLIC_MAPPLS_MAP_API}/map_sdk?layer=vector&v=3.0`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <head>
              <Script src={MapScriptUrl} strategy="beforeInteractive"></Script>
              {/* <Script src={MapScriptUrl} defer async strategy="beforeInteractive"></Script> */}
            </head>

            {children}
          </ThemeProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
